import { Icon } from '@iconify/react';

export const BY_STATUS = [
  { id: 0, idd: 0, value: 'ALL', label: 'All', others: "", what: "STATUS" },
  { id: 1, idd: 1, value: 'ACTIVE', label: 'Active', others: "", what: "STATUS" },
  { id: 2, idd: 2, value: 'PENDING', label: 'Pending', others: "", what: "STATUS" },
  { id: 3, idd: 3, value: 'ACTIVEPENDING', label: 'Active & Pending', others: "", what: "STATUS" },
  { id: 4, idd: 4, value: 'DISABLED', label: 'Disabled', others: "", what: "STATUS" },
];
 
export const BY_ORDER = [
  { id: 0, value: 'ASC', label: <Icon icon="bxs:up-arrow"/> },
  { id: 1, value: 'DESC', label: <Icon icon="bxs:down-arrow"/> },
];

// ====================== +++ ITEMS +++ ====================================

export const BY_ACCOUNTS = [
  { id: 0,idd: 0, value: 'NONE', label: 'ID', others: "", what: "ACCOUNTS" },
  { id: 1,idd: 1, value: 'app.name', label: 'Application', others: "", what: "ACCOUNTS" },
  { id: 2,idd: 2, value: 'a.accountID', label: 'Account ID', others: "", what: "ACCOUNTS" },
  { id: 3,idd: 3, value: 'a.accountNickname', label: 'Nickname', others: "", what: "ACCOUNTS" },
  { id: 4,idd: 4, value: 'a.accountRole', label: 'Role', others: "", what: "ACCOUNTS" },
  { id: 5,idd: 5, value: 'a.status', label: 'Status', others: "", what: "ACCOUNTS" },
];

export const BY_UPLINES = [
  { id: 0,idd: 0, value: 'NONE', label: 'ID', others: "", what: "UPLINES" },
  { id: 1,idd: 1, value: 'app.name', label: 'Application', others: "", what: "UPLINES" },
  { id: 2,idd: 2, value: 'up.clubID', label: 'Club ID', others: "", what: "UPLINES" },
  { id: 3,idd: 3, value: 'c.name', label: 'Club', others: "", what: "UPLINES" },
  { id: 4,idd: 4, value: 'up.downlineID', label: 'Player ID', others: "", what: "UPLINES" },
  { id: 5,idd: 5, value: 'up.uplineID', label: 'Upline ID', others: "", what: "UPLINES" },
  { id: 6,idd: 6, value: '(SELECT aa.accountNickname FROM accounts AS aa WHERE aa.accountID = up.downlineID)', label: 'Player Nickname', others: "", what: "UPLINES" },
  { id: 7,idd: 7, value: '(SELECT aa.accountNickname FROM accounts AS aa WHERE aa.accountID = up.uplineID)', label: 'Upline Nickname', others: "", what: "UPLINES" },
  { id: 8,idd: 8, value: 'up.percentage', label: 'Percentage', others: "", what: "UPLINES" },
  { id: 9,idd: 9, value: 'up.status', label: 'Status', others: "", what: "UPLINES" },
];

export const BY_HISTORY = [
  { id: 0,idd: 0, value: 'NONE', label: 'ID', others: "", what: "HISTORY" },
  { id: 1,idd: 1, value: 'u.nickname', label: 'Nickname', others: "", what: "HISTORY" },
  { id: 2,idd: 2, value: 'r.name', label: 'Role', others: "", what: "HISTORY" },
  { id: 3,idd: 3, value: 'h.datetime', label: 'Date stamp', others: "", what: "HISTORY" },
  { id: 4,idd: 4, value: 'h.gadget', label: 'Gadget', others: "", what: "HISTORY" },
  { id: 4,idd: 4, value: 'h.timezone', label: 'Timezone', others: "", what: "HISTORY" },
  { id: 5,idd: 5, value: 'h.action', label: 'Action', others: "", what: "HISTORY" },
  { id: 5,idd: 5, value: 'h.for', label: 'For', others: "", what: "HISTORY" },
];

export const BY_FXAPPLY = [
  { id: 0,idd: 0, value: 'This', label: 'This item'},
  { id: 1,idd: 1, value: 'Clubs', label: 'To all same clubs'},
  { id: 2,idd: 2, value: 'Applications', label: 'To all same apps'},
  { id: 3,idd: 3, value: 'Players', label: 'To all same player' },
  { id: 4,idd: 4, value: 'Date Closed', label: 'To all same date'},
  { id: 5,idd: 5, value: 'All', label: 'To all'},
];

export const CURRENCIES = [
                            { "code": "AED", "country": "United Arab Emirates" },
                            { "code": "AFN", "country": "Afghanistan" },
                            { "code": "ALL", "country": "Albania" },
                            { "code": "AMD", "country": "Armenia" },
                            { "code": "ANG", "country": "Netherlands Antilles" },
                            { "code": "AOA", "country": "Angola" },
                            { "code": "ARS", "country": "Argentina" },
                            { "code": "AUD", "country": "Australia" },
                            { "code": "AWG", "country": "Aruba" },
                            { "code": "AZN", "country": "Azerbaijan" },
                            { "code": "BAM", "country": "Bosnia and Herzegovina" },
                            { "code": "BBD", "country": "Barbados" },
                            { "code": "BDT", "country": "Bangladesh" },
                            { "code": "BGN", "country": "Bulgaria" },
                            { "code": "BHD", "country": "Bahrain" },
                            { "code": "BIF", "country": "Burundi" },
                            { "code": "BMD", "country": "Bermuda" },
                            { "code": "BND", "country": "Brunei" },
                            { "code": "BOB", "country": "Bolivia" },
                            { "code": "BRL", "country": "Brazil" },
                            { "code": "BSD", "country": "Bahamas" },
                            { "code": "BTN", "country": "Bhutan" },
                            { "code": "BWP", "country": "Botswana" },
                            { "code": "BYN", "country": "Belarus" },
                            { "code": "BZD", "country": "Belize" },
                            { "code": "CAD", "country": "Canada" },
                            { "code": "CDF", "country": "Congo, Democratic Republic of the" },
                            { "code": "CHE", "country": "WIR Euro" },
                            { "code": "CHF", "country": "Switzerland" },
                            { "code": "CHW", "country": "WIR Franc" },
                            { "code": "CLP", "country": "Chile" },
                            { "code": "CNY", "country": "China" },
                            { "code": "COP", "country": "Colombia" },
                            { "code": "CRC", "country": "Costa Rica" },
                            { "code": "CUC", "country": "Cuba" },
                            { "code": "CUP", "country": "Cuba" },
                            { "code": "CVE", "country": "Cape Verde" },
                            { "code": "CZK", "country": "Czech Republic" },
                            { "code": "DJF", "country": "Djibouti" },
                            { "code": "DKK", "country": "Denmark" },
                            { "code": "DOP", "country": "Dominican Republic" },
                            { "code": "DZD", "country": "Algeria" },
                            { "code": "EGP", "country": "Egypt" },
                            { "code": "ERN", "country": "Eritrea" },
                            { "code": 'EUR', "country": 'European Union' },
                            { "code": "ETB", "country": "Ethiopia" },
                            { "code": "EUR", "country": "Eurozone" },
                            { "code": "FJD", "country": "Fiji" },
                            { "code": "FKP", "country": "Falkland Islands" },
                            { "code": "FOK", "country": "Faroe Islands" },
                            { "code": "GBP", "country": "United Kingdom" },
                            { "code": "GEL", "country": "Georgia" },
                            { "code": "GGP", "country": "Guernsey" },
                            { "code": "GHS", "country": "Ghana" },
                            { "code": "GIP", "country": "Gibraltar" },
                            { "code": "GMD", "country": "Gambia" },
                            { "code": "GNF", "country": "Guinea" },
                            { "code": "GTQ", "country": "Guatemala" },
                            { "code": "GYD", "country": "Guyana" },
                            { "code": "HKD", "country": "Hong Kong" },
                            { "code": "HNL", "country": "Honduras" },
                            { "code": "HRK", "country": "Croatia" },
                            { "code": "HTG", "country": "Haiti" },
                            { "code": "HUF", "country": "Hungary" },
                            { "code": "IDR", "country": "Indonesia" },
                            { "code": "ILS", "country": "Israel" },
                            { "code": "IMP", "country": "Isle of Man" },
                            { "code": "INR", "country": "India" },
                            { "code": "IQD", "country": "Iraq" },
                            { "code": "IRR", "country": "Iran" },
                            { "code": "ISK", "country": "Iceland" },
                            { "code": "JEP", "country": "Jersey" },
                            { "code": "JMD", "country": "Jamaica" },
                            { "code": "JOD", "country": "Jordan" },
                            { "code": "JPY", "country": "Japan" },
                            { "code": "KES", "country": "Kenya" },
                            { "code": "KGS", "country": "Kyrgyzstan" },
                            { "code": "KHR", "country": "Cambodia" },
                            { "code": "KID", "country": "Kiribati" },
                            { "code": "KMF", "country": "Comoros" },
                            { "code": "KRW", "country": "South Korea" },
                            { "code": "KWD", "country": "Kuwait" },
                            { "code": "KYD", "country": "Cayman Islands" },
                            { "code": "KZT", "country": "Kazakhstan" },
                            { "code": "LAK", "country": "Laos" },
                            { "code": "LBP", "country": "Lebanon" },
                            { "code": "LKR", "country": "Sri Lanka" },
                            { "code": "LRD", "country": "Liberia" },
                            { "code": "LSL", "country": "Lesotho" },
                            { "code": "LYD", "country": "Libya" },
                            { "code": "MAD", "country": "Morocco" },
                            { "code": "MDL", "country": "Moldova" },
                            { "code": "MGA", "country": "Madagascar" },
                            { "code": "MKD", "country": "North Macedonia" },
                            { "code": "MMK", "country": "Myanmar" },
                            { "code": "MNT", "country": "Mongolia" },
                            { "code": "MOP", "country": "Macau" },
                            { "code": "MRU", "country": "Mauritania" },
                            { "code": "MUR", "country": "Mauritius" },
                            { "code": "MVR", "country": "Maldives" },
                            { "code": "MWK", "country": "Malawi" },
                            { "code": "MXN", "country": "Mexico" },
                            { "code": "MYR", "country": "Malaysia" },
                            { "code": "MZN", "country": "Mozambique" },
                            { "code": "NAD", "country": "Namibia" },
                            { "code": "NGN", "country": "Nigeria" },
                            { "code": "NIO", "country": "Nicaragua" },
                            { "code": "NOK", "country": "Norway" },
                            { "code": "NPR", "country": "Nepal" },
                            { "code": "NZD", "country": "New Zealand" },
                            { "code": "OMR", "country": "Oman" },
                            { "code": "PAB", "country": "Panama" },
                            { "code": "PEN", "country": "Peru" },
                            { "code": "PGK", "country": "Papua New Guinea" },
                            { "code": "PHP", "country": "Philippines" },
                            { "code": "PKR", "country": "Pakistan" },
                            { "code": "PLN", "country": "Poland" },
                            { "code": "PYG", "country": "Paraguay" },
                            { "code": "QAR", "country": "Qatar" },
                            { "code": "RON", "country": "Romania" },
                            { "code": "RSD", "country": "Serbia" },
                            { "code": "RUB", "country": "Russia" },
                            { "code": "RWF", "country": "Rwanda" },
                            { "code": "SAR", "country": "Saudi Arabia" },
                            { "code": "SBD", "country": "Solomon Islands" },
                            { "code": "SCR", "country": "Seychelles" },
                            { "code": "SDG", "country": "Sudan" },
                            { "code": "SEK", "country": "Sweden" },
                            { "code": "SGD", "country": "Singapore" },
                            { "code": "SHP", "country": "Saint Helena" },
                            { "code": "SLL", "country": "Sierra Leone" },
                            { "code": "SOS", "country": "Somalia" },
                            { "code": "SRD", "country": "Suriname" },
                            { "code": "SSP", "country": "South Sudan" },
                            { "code": "STN", "country": "São Tomé and Príncipe" },
                            { "code": "SYP", "country": "Syria" },
                            { "code": "SZL", "country": "Eswatini" },
                            { "code": "THB", "country": "Thailand" },
                            { "code": "TJS", "country": "Tajikistan" },
                            { "code": "TKM", "country": "Turkmenistan" },
                            { "code": "TMT", "country": "Turkmenistan" },
                            { "code": "TND", "country": "Tunisia" },
                            { "code": "TOP", "country": "Tonga" },
                            { "code": "TRY", "country": "Turkey" },
                            { "code": "TTD", "country": "Trinidad and Tobago" },
                            { "code": "TVD", "country": "Tuvalu" },
                            { "code": "TZS", "country": "Tanzania" },
                            { "code": "UAH", "country": "Ukraine" },
                            { "code": "UGX", "country": "Uganda" },
                            { "code": 'USD', "country": 'United States' },
                            { "code": "VND", "country": "Vietnam" },
                            { "code": "VES", "country": "Venezuela" },
                            { "code": "VUV", "country": "Vanuatu" },
                            { "code": "WST", "country": "Samoa" },
                            { "code": "XAG", "country": "Silver" },
                            { "code": "XAU", "country": "Gold" },
                            { "code": "XCD", "country": "East Caribbean dollar" },
                            { "code": "XDR", "country": "Special Drawing Rights" },
                            { "code": "XOF", "country": "West African CFA franc" },
                            { "code": "XPF", "country": "CFP franc" },
                            { "code": "YER", "country": "Yemen" },
                            { "code": "ZAR", "country": "South Africa" },
                            { "code": "ZMW", "country": "Zambia" },
                            { "code": "ZWL", "country": "Zimbabwe" },
                      ]


















